CREATE TABLE `CLASS`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME` VARCHAR(255) NOT NULL,
    `DESCRIPTION` TEXT NOT NULL
);
CREATE TABLE `INVENTORY`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME` VARCHAR(255) NOT NULL,
    `DESCRIPTION` TEXT NOT NULL,
    `TYPE` VARCHAR(255) NOT NULL
);
CREATE TABLE `CHARACTER_SHEET`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `CHARACTER_NAME` VARCHAR(255) NOT NULL,
    `PRONOUNS` VARCHAR(255) NULL,
    `BACKGROUND` TEXT NULL,
    `LEVEL` INT NOT NULL DEFAULT '1',
    `CLASS` INT NOT NULL,
    `RACE` INT NOT NULL,
    `STRENGTH` INT NOT NULL DEFAULT '1',
    `DEXTERITY` INT NOT NULL DEFAULT '1',
    `RESILIENCE` INT NOT NULL DEFAULT '1',
    `MAGIC` INT NOT NULL DEFAULT '1',
    `CUTENESS` INT NOT NULL DEFAULT '1'
);
CREATE TABLE `RACE`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME` VARCHAR(255) NOT NULL,
    `DESCRIPTION` TEXT NOT NULL
);
CREATE TABLE `INVENTORY_LIST`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `ITEM_ID` INT NOT NULL,
    `CHARACTER_ID` INT NOT NULL
);
ALTER TABLE
    `INVENTORY_LIST` ADD CONSTRAINT `inventory_list_character_id_foreign` FOREIGN KEY(`CHARACTER_ID`) REFERENCES `CHARACTER_SHEET`(`id`);
ALTER TABLE
    `CHARACTER_SHEET` ADD CONSTRAINT `character_sheet_class_foreign` FOREIGN KEY(`CLASS`) REFERENCES `CLASS`(`id`);
ALTER TABLE
    `CHARACTER_SHEET` ADD CONSTRAINT `character_sheet_race_foreign` FOREIGN KEY(`RACE`) REFERENCES `RACE`(`id`);
ALTER TABLE
    `INVENTORY_LIST` ADD CONSTRAINT `inventory_list_inventory_id_foreign` FOREIGN KEY(`ITEM_ID`) REFERENCES `INVENTORY`(`id`);